import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';
import { AuditResult } from '../../data/audit';

const styles = StyleSheet.create({
    page: {
        padding: 50,
        backgroundColor: '#ffffff',
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 40,
    },
    title: {
        fontSize: 24,
        marginBottom: 10,
        fontFamily: 'Helvetica-Bold',
    },
    subtitle: {
        fontSize: 12,
        color: '#666666',
    },
    scoreSection: {
        marginTop: 20,
        marginBottom: 40,
        padding: 20,
        backgroundColor: '#F3F4F6',
        borderRadius: 8,
        textAlign: 'center',
    },
    totalScore: {
        fontSize: 48,
        fontFamily: 'Helvetica-Bold',
        color: '#000000',
    },
    scoreLabel: {
        fontSize: 14,
        color: '#F9541F', // Brand primary
        marginTop: 5,
        textTransform: 'uppercase',
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: 'Helvetica-Bold',
        marginBottom: 15,
        marginTop: 25,
        borderBottom: '1 solid #E5E7EB',
        paddingBottom: 8,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
        alignItems: 'center',
    },
    label: {
        fontSize: 12,
        width: '40%',
    },
    barContainer: {
        width: '40%',
        height: 8,
        backgroundColor: '#E5E7EB',
        borderRadius: 4,
    },
    bar: {
        height: '100%',
        backgroundColor: '#F9541F',
        borderRadius: 4,
    },
    value: {
        fontSize: 12,
        fontFamily: 'Helvetica-Bold',
        width: '10%',
        textAlign: 'right',
    },
    text: {
        fontSize: 12,
        lineHeight: 1.5,
        color: '#333333',
        marginBottom: 10,
    },
    highlightBox: {
        backgroundColor: '#FFF1ED', // Primary light
        padding: 15,
        borderRadius: 6,
        marginBottom: 10,
    },
    highlightTitle: {
        fontSize: 14,
        fontFamily: 'Helvetica-Bold',
        color: '#F9541F',
        marginBottom: 5,
    }
});

interface AuditPDFProps {
    result: AuditResult;
}

export const AuditPDF: React.FC<AuditPDFProps> = ({ result }) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* Header */}
            <View style={styles.header}>
                <Text style={styles.title}>Marketing Performance Audit</Text>
                <Text style={styles.subtitle}>Generated by Marketing Extension on {new Date().toLocaleDateString()}</Text>
            </View>

            {/* Score */}
            <View style={styles.scoreSection}>
                <Text style={styles.totalScore}>{result.totalScore}/100</Text>
                <Text style={styles.scoreLabel}>{result.maturityLabel} Stage</Text>
            </View>

            {/* Breakdown */}
            <View>
                <Text style={styles.sectionTitle}>Performance Breakdown</Text>
                {Object.entries(result.subScores).map(([cat, score]) => (
                    <View key={cat} style={styles.row}>
                        <Text style={styles.label}>{cat}</Text>
                        <View style={styles.barContainer}>
                            <View style={[styles.bar, { width: `${(score / 20) * 100}%` }]} />
                        </View>
                        <Text style={styles.value}>{score}/20</Text>
                    </View>
                ))}
            </View>

            {/* Priorities */}
            <View>
                <Text style={styles.sectionTitle}>Top 3 Priorities</Text>
                {result.topPriorities.map((p, i) => (
                    <View key={i} style={styles.highlightBox}>
                        <Text style={styles.highlightTitle}>0{i + 1}. {p}</Text>
                        <Text style={styles.text}>
                            Focus on improving this area to unlock the next stage of growth.
                        </Text>
                    </View>
                ))}
            </View>

            {/* Recommendations */}
            <View>
                <Text style={styles.sectionTitle}>Recommended Focus</Text>
                {result.recommendedServices.map((rec, i) => (
                    <Text key={i} style={styles.text}>• {rec.name}</Text>
                ))}
            </View>

            <View style={{ marginTop: 40, borderTop: '1 solid #ccc', paddingTop: 20 }}>
                <Text style={{ fontSize: 10, color: '#999' }}>
                    marketingextension.com | Growth Marketing & Demand Generation Partner
                </Text>
            </View>
        </Page>
    </Document>
);
